server:
  port: 8080

spring:
  cloud:
    sentinel:
      transport:
        dashboard: his-sentinel.his:8080
  rabbitmq:
    host: his-rabbitmq.his
    port: 15672
    username: admin
    password: admin
  redis:
    host: his-redis.his
#阿里云 短信
aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI0YbQf3pX8WqC
    secret: jX8D04DmDI3gGKjW5kaFYSzugfqmmT
